#!/usr/bin/env bash
set -euo pipefail

# Self-Evolution Governor — Interactive Installer
# Usage: bash setup.sh [--yes] [--hermes-home /path/to/.hermes]

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
AUTO_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --hermes-home) HERMES_HOME="$2"; shift 2 ;;
        --yes|-y) AUTO_YES=true; shift ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

SKILL_DIR="$HERMES_HOME/skills/dogfood/self-evolution-governor"
STATE_DIR="$HERMES_HOME/state/evolution"
PIPELINE_SCRIPT="$SKILL_DIR/scripts/self_evolution_daily_pipeline.py"

echo "=============================="
echo " Self-Evolution Governor 安装向导"
echo "=============================="
echo ""

# ── Step 1: Install skill files ──
echo "📦 [1/5] 安装 skill 文件..."
mkdir -p "$STATE_DIR/score_explanations" "$SKILL_DIR/scripts" "$SKILL_DIR/templates"
cp "$SOURCE_DIR/skills/self-evolution-governor/SKILL.md" "$SKILL_DIR/"
cp "$SOURCE_DIR/skills/self-evolution-governor/scripts/"*.py "$SKILL_DIR/scripts/"
cp "$SOURCE_DIR/skills/self-evolution-governor/templates/proposal.yaml" "$SKILL_DIR/templates/"
chmod 755 "$STATE_DIR"
echo "   ✅ Skill installed at: $SKILL_DIR"

# ── Step 2: Initialize state files ──
echo -e "\n📁 [2/5] 初始化状态文件..."
[ -f "$STATE_DIR/signals.jsonl" ]      || touch "$STATE_DIR/signals.jsonl"
[ -f "$STATE_DIR/speak_quota.json" ]   || echo '{"date":"","suggestions":0,"strategic":0}' > "$STATE_DIR/speak_quota.json"
[ -f "$STATE_DIR/agenda_speak_quota.json" ] || echo '{"date":"","surfaces":0,"surface_history":{}}' > "$STATE_DIR/agenda_speak_quota.json"
[ -f "$STATE_DIR/self_agenda.yaml" ]   || cp "$SOURCE_DIR/demo/self_agenda.yaml.example" "$STATE_DIR/self_agenda.yaml"
[ -f "$STATE_DIR/proposal_queue.yaml" ] || echo '{"version":1,"updated_at":"","proposals":[]}' > "$STATE_DIR/proposal_queue.yaml"
[ -f "$STATE_DIR/agenda_candidates.yaml" ] || echo "version: 3\ngenerated_at: ''\nshadow_mode: true\ncandidates: []" > "$STATE_DIR/agenda_candidates.yaml"
[ -f "$STATE_DIR/evolution_journal.md" ] || echo "# Self-Evolution Governor — Evolution Journal\nInitialized on $(date '+%Y-%m-%d %H:%M')\n" > "$STATE_DIR/evolution_journal.md"
[ -f "$STATE_DIR/HERMES_FOCUS.md" ]   || cat > "$STATE_DIR/HERMES_FOCUS.md" <<FOCUS
# HERMES_FOCUS.md

Last updated: $(date '+%Y-%m-%d %H:%M')
Generated by: self-evolution-governor

## Current Operating Focus
1. Self-evolution-governor initialized — no errors, no corrections detected.
FOCUS
[ -f "$STATE_DIR/runtime_digest.md" ] || cat > "$STATE_DIR/runtime_digest.md" <<DIGEST
# Hermes Runtime Digest

Last updated: $(date '+%Y-%m-%d %H:%M')
Valid until: $(date -d '+24 hours' '+%Y-%m-%d %H:%M')

## Runtime Guidance
- Self-evolution outputs are advisory unless approved by the user.
- Route executable changes through user approval and ops-gate.
DIGEST
echo "   ✅ State directory ready at: $STATE_DIR"

# ── Step 3: Install plugin (optional, interactive) ──
echo -e "\n🔌 [3/5] Runtime digest 注入插件"
if [ -x "$(command -v hermes)" ]; then
    PLUGIN_SRC="$SOURCE_DIR/plugin/hermes-self-evolution"
    if $AUTO_YES; then
        REPLY="y"
    else
        read -rp "   是否安装 Hermes 插件（自动注入 runtime_digest 到每次会话）? [Y/n] " REPLY
    fi
    REPLY="${REPLY:-y}"
    if [[ "$REPLY" =~ ^[Yy] ]]; then
        if hermes plugins list 2>/dev/null | grep -q "hermes-self-evolution"; then
            echo "   ⏭️  插件已安装，跳过"
        else
            hermes plugins install "$PLUGIN_SRC" --enable 2>&1 && echo "   ✅ 插件安装成功" || echo "   ⚠️  插件安装失败（手动：hermes plugins install $PLUGIN_SRC --enable）"
        fi
    else
        echo "   ⏭️  跳过插件安装"
    fi
else
    echo "   ⏭️  hermes 命令未找到，跳过插件安装"
fi

# ── Step 4: Cron setup (interactive) ──
echo -e "\n⏰ [4/5] 定时任务设置"
echo "   Pipeline 每天 04:00 自动运行（12步: collect→unmatched→cluster→preview→apply→digest→mature→route→speak→console→restart→delivery）"

if [ -x "$(command -v hermes)" ]; then
    if $AUTO_YES; then
        REPLY="y"
    else
        read -rp "   是否创建 cron 任务? [Y/n] " REPLY
    fi
    REPLY="${REPLY:-y}"
    if [[ "$REPLY" =~ ^[Yy] ]]; then
        EXISTING=$(hermes cron list 2>/dev/null | grep "self-evolution-daily" || true)
        if [ -n "$EXISTING" ]; then
            echo "   ⏭️  已存在 self-evolution-daily 任务，跳过"
        else
            hermes cron create \
                --schedule "0 4 * * *" \
                --script "$PIPELINE_SCRIPT" \
                --name "self-evolution-daily" \
                --no-agent 2>&1 && echo "   ✅ Cron 任务已创建（每天 04:00）" || echo "   ⚠️  创建失败，可手动添加"
        fi
    else
        echo "   ⏭️  跳过 cron 设置"
    fi
else
    echo "   ⏭️  hermes 命令未找到，跳过 cron 设置"
fi

# ── Step 5: Smoke test ──
echo -e "\n🧪 [5/5] 运行测试"
if $AUTO_YES; then
    REPLY="y"
else
    read -rp "   是否运行一次采集测试? [Y/n] " REPLY
fi
REPLY="${REPLY:-y}"
if [[ "$REPLY" =~ ^[Yy] ]]; then
    cd "$SKILL_DIR/scripts"
    echo "   ▶ 收集信号..."
    python3 collect_signals.py 2>&1 | tail -1
    echo "   ▶ 生成运行时摘要..."
    python3 build_runtime_digest.py 2>&1 | tail -1
    echo "   ▶ 检查结果..."
    SIG_COUNT=$(wc -l < "$STATE_DIR/signals.jsonl")
    if [ "$SIG_COUNT" -gt 0 ]; then
        echo "   ✅ 测试通过 — signals.jsonl: $SIG_COUNT 行"
    else
        echo "   ⚠️  signals.jsonl 为空，检查日志"
    fi
else
    echo "   ⏭️  跳过测试"
fi

# ── Summary ──
echo ""
echo "=============================="
echo " ✅ 安装完成"
echo "=============================="
echo "   Skill:      $SKILL_DIR"
echo "   状态文件:    $STATE_DIR"
echo "   Pipeline脚本: $PIPELINE_SCRIPT"
echo ""
echo "   后续操作:"
echo "   • 查看 runtime digest:     cat $STATE_DIR/runtime_digest.md"
echo "   • 查看议程:               cat $STATE_DIR/self_agenda.yaml"
echo "   • 加载 skill:             hermes -s self-evolution-governor"
echo "   • 手动跑 pipeline:        python3 $PIPELINE_SCRIPT"
echo "=============================="
