#!/usr/bin/env bash
set -euo pipefail

# Self-Evolution Governor — Installer
# Usage: bash setup.sh [--hermes-home /path/to/.hermes]

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --hermes-home) HERMES_HOME="$2"; shift 2 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

echo "📦 Installing self-evolution-governor to $HERMES_HOME"

# 1. Create state directories
mkdir -p "$HERMES_HOME/state/evolution/score_explanations"
chmod 755 "$HERMES_HOME/state/evolution"

# 2. Install skill
SKILL_DIR="$HERMES_HOME/skills/dogfood/self-evolution-governor"
mkdir -p "$SKILL_DIR/scripts" "$SKILL_DIR/templates"
cp "$SOURCE_DIR/skills/self-evolution-governor/SKILL.md" "$SKILL_DIR/"
cp -r "$SOURCE_DIR/skills/self-evolution-governor/scripts/"*.py "$SKILL_DIR/scripts/"
cp "$SOURCE_DIR/skills/self-evolution-governor/templates/proposal.yaml" "$SKILL_DIR/templates/"

# 3. Initialize state files (only if they don't exist)
STATE_DIR="$HERMES_HOME/state/evolution"
[ -f "$STATE_DIR/signals.jsonl" ] || touch "$STATE_DIR/signals.jsonl"
[ -f "$STATE_DIR/speak_quota.json" ] || echo '{"date": "", "suggestions": 0, "strategic": 0}' > "$STATE_DIR/speak_quota.json"
[ -f "$STATE_DIR/agenda_speak_quota.json" ] || echo '{"date": "", "surfaces": 0, "surface_history": {}}' > "$STATE_DIR/agenda_speak_quota.json"
[ -f "$STATE_DIR/self_agenda.yaml" ] || cp "$SOURCE_DIR/demo/self_agenda.yaml.example" "$STATE_DIR/self_agenda.yaml"
[ -f "$STATE_DIR/proposal_queue.yaml" ] || echo '{"version": 1, "updated_at": "", "proposals": []}' > "$STATE_DIR/proposal_queue.yaml"
[ -f "$STATE_DIR/agenda_candidates.yaml" ] || echo "version: 3\ngenerated_at: ''\nshadow_mode: true\ncandidates: []" > "$STATE_DIR/agenda_candidates.yaml"
[ -f "$STATE_DIR/evolution_journal.md" ] || echo "# Self-Evolution Governor — Evolution Journal\n\nInitialized on $(date '+%Y-%m-%d %H:%M')\n" > "$STATE_DIR/evolution_journal.md"
[ -f "$STATE_DIR/HERMES_FOCUS.md" ] || echo "# HERMES_FOCUS.md\n\nLast updated: $(date '+%Y-%m-%d %H:%M')\nGenerated by: self-evolution-governor\n\n## Current Operating Focus\n1. Self-evolution-governor initialized\n" > "$STATE_DIR/HERMES_FOCUS.md"
[ -f "$STATE_DIR/runtime_digest.md" ] || echo "# Hermes Runtime Digest\n\nLast updated: $(date '+%Y-%m-%d %H:%M')\nValid until: $(date -d '+24 hours' '+%Y-%m-%d %H:%M')\n\n## Runtime Guidance\n- Self-evolution outputs are advisory unless approved by the user.\n- Route executable changes through user approval and ops-gate.\n" > "$STATE_DIR/runtime_digest.md"

# 4. Set up cron jobs (optional, asks user)
echo ""
echo "⏰ Cron job setup (self-evolution pipeline)"
echo "   The pipeline requires these cron jobs:"
echo "     1. Daily pipeline at 04:00 (12-step: collect → unmatched → cluster → preview → apply → digest → mature → route → speak → console → restart → delivery)"
echo "     2. Weekly strategy on Monday 07:00"
echo ""
echo "   To set them up, install via Hermes cron (recommended):"
echo ""
echo "     hermes cron create \\"
echo '       --schedule "0 4 * * *" \'
echo '       --script "'"$SOURCE_DIR"'/scripts/self_evolution_daily_pipeline.py" \'
echo '       --name "self-evolution-daily" \'
echo '       --no-agent'
echo ""
echo "   OR add to crontab manually:"
echo "   # Self-Evolution Governor daily pipeline (12 steps)"
echo "   0 4 * * * cd $SOURCE_DIR/scripts && HERMES_HOME=$HERMES_HOME python3 self_evolution_daily_pipeline.py"
echo ""

# 5. Runtime digest injection (optional)
echo "🔌 Runtime digest injection"
echo "   For automatic injection of runtime_digest.md into every session,"
echo "   install the optional Hermes plugin:"
echo "     hermes plugins install $SOURCE_DIR/plugin/hermes-self-evolution --enable"
echo ""
echo "   OR manually add to your config.yaml hooks:"
echo '   hooks:'
echo '     on_session_start:'
echo '       - command: "cat $HERMES_HOME/state/evolution/runtime_digest.md"'
echo ""

# 6. Verify installation
echo "✅ Installation complete!"
echo "   Skill installed at: $SKILL_DIR"
echo "   State directory: $STATE_DIR"
echo ""
echo "   Next steps:"
echo "     1. Run a test: cd $SKILL_DIR/scripts && python3 collect_signals.py"
echo "     2. Set up cron jobs (see above)"
echo "     3. Install the optional plugin for auto-injection"
echo "     4. Load the skill: hermes -s self-evolution-governor"
